GOOSE_PROVIDER: anthropic
GOOSE_MODE: auto
GOOSE_MODEL: claude-3-7-sonnet-latest
extensions:
  computercontroller:
    enabled: true
    name: computercontroller
    timeout: 300
    type: builtin
  developer:
    enabled: true
    name: developer
    timeout: 300
    type: builtin
  memory:
    enabled: true
    name: memory
    timeout: 300
    type: builtin
experiments:
  GOOSE_SMART_APPROVE: true
GOOSE_CLI_MIN_PRIORITY: 0.0
