GOOSE_PROVIDER: anthropic
GOOSE_MODEL: claude-3-7-sonnet-latest
extensions:
  developer:
    enabled: true
    name: developer
    timeout: 300
    type: builtin
  fetch:
    args:
      - mcp-server-fetch
    cmd: uvx
    enabled: true
    envs: {}
    name: fetch
    timeout: 300
    type: stdio
  memory:
    enabled: true
    name: memory
    timeout: 300
    type: builtin
