GOOSE_MODE: auto
GOOSE_MODEL: openai/gpt-4.1
GOOSE_CLI_MIN_PRIORITY: 0.0
GOOSE_PROVIDER: openrouter
experiments:
  GOOSE_SMART_APPROVE: true
extensions:
  computercontroller:
    enabled: true
    name: computercontroller
    timeout: 300
    type: builtin
  developer:
    enabled: true
    name: developer
    timeout: 300
    type: builtin
  github:
    args:
    - run
    - -i
    - --rm
    - -e
    - GITHUB_PERSONAL_ACCESS_TOKEN
    - ghcr.io/github/github-mcp-server
    cmd: docker
    enabled: true
    envs: {}
    name: github
    timeout: 300
    type: stdio
  memory:
    enabled: true
    name: memory
    timeout: 300
    type: builtin
  puppeteer:
    args:
    - -y
    - '@modelcontextprotocol/server-puppeteer'
    cmd: npx
    enabled: true
    envs: {}
    name: puppeteer
    timeout: 300
    type: stdio
  todoist:
    args:
    - -y
    - '@abhiz123/todoist-mcp-server'
    cmd: npx
    enabled: true
    envs: {}
    name: todoist
    timeout: 300
    type: stdio
